### ISSUE TITLE
Any reason you do not use the driver available as AUR

### ISSUE THREAD

**Issue by chopfitzroy** [eriknelson/arch_onyx_pro#1]
When googling for System76 arch both this AUR: https://aur.archlinux.org/packages/system76-driver/ and your repo came up, I am wondering if there is any reason you are not taking advantage of this?

Cheers.

**Comment by eriknelson** [comment]
Hi! I honestly don't recall using this package, but I'm hoping to update the tutorial soon since I've seen a sudden surge of interest. Will investigate.
